import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Sparkles, AlertTriangle, CheckCircle, Volume2, Users, Bot, Send } from 'lucide-react';
import { candidatesApi } from '../services/api';

function ApplicantInterview() {
  const navigate = useNavigate();
  const [candidateId, setCandidateId] = useState(null);
  const [submitting, setSubmitting] = useState(false);
  const [selectedFlags, setSelectedFlags] = useState([]);
  const [interviewScore, setInterviewScore] = useState(85);
  const [summary, setSummary] = useState('Mock interview completed for testing purposes. This is a placeholder summary that would normally be generated by AI based on the interview responses and performance analysis.');

  useEffect(() => {
    // Get candidate ID from session
    const id = sessionStorage.getItem('candidate_id');
    if (!id) {
      navigate('/applicant/code');
      return;
    }
    setCandidateId(id);
  }, [navigate]);

  const toggleFlag = (flagType) => {
    setSelectedFlags(prev => {
      if (prev.some(f => f.type === flagType)) {
        return prev.filter(f => f.type !== flagType);
      } else {
        return [...prev, { type: flagType, severity: 'high' }];
      }
    });
  };

  const isFlagSelected = (flagType) => {
    return selectedFlags.some(f => f.type === flagType);
  };

  const handleSubmitInterview = async () => {
    try {
      setSubmitting(true);
      
      // Update candidate with interview data
      await candidatesApi.update(candidateId, {
        status: 'Interviewed',
        interview_score: interviewScore,
        flags: selectedFlags,
        summary: summary,
        transcript_url: '/transcripts/mock-transcript.txt'
      });

      // Navigate to profile to see results
      navigate('/applicant/profile');
    } catch (err) {
      alert(`Error: ${err.message}`);
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-dark-950">
      {/* Header */}
      <header className="bg-dark-900 shadow-sm border-b border-dark-800">
        <div className="max-w-7xl mx-auto px-8 py-6">
          <div className="flex items-center space-x-2">
            <Sparkles className="w-8 h-8 text-primary-400" />
            <h1 className="text-2xl font-bold text-white">Candidly</h1>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-8 py-12">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-bold text-white mb-4">Mock Interview Testing</h2>
          <p className="text-gray-400">
            Select flags to test the interview completion with different scenarios
          </p>
        </div>

        {/* Flag Selection Cards */}
        <div className="bg-dark-800 rounded-lg shadow-sm border border-dark-700 p-8 mb-8">
          <h3 className="text-xl font-bold text-white mb-6">Select Interview Flags</h3>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {/* Sound Flag */}
            <button
              onClick={() => toggleFlag('sound')}
              className={`p-6 rounded-lg border-2 transition-all ${
                isFlagSelected('sound')
                  ? 'bg-yellow-900/30 border-yellow-600'
                  : 'bg-dark-900 border-dark-700 hover:border-dark-600'
              }`}
            >
              <div className="flex flex-col items-center space-y-3">
                <Volume2 className={`w-12 h-12 ${isFlagSelected('sound') ? 'text-yellow-400' : 'text-gray-500'}`} />
                <div className="text-center">
                  <p className={`font-semibold ${isFlagSelected('sound') ? 'text-yellow-400' : 'text-gray-400'}`}>
                    Sound Flag
                  </p>
                  <p className="text-xs text-gray-500 mt-1">Suspicious sounds detected</p>
                </div>
                {isFlagSelected('sound') && (
                  <CheckCircle className="w-6 h-6 text-yellow-400" />
                )}
              </div>
            </button>

            {/* Face Flag */}
            <button
              onClick={() => toggleFlag('face')}
              className={`p-6 rounded-lg border-2 transition-all ${
                isFlagSelected('face')
                  ? 'bg-orange-900/30 border-orange-600'
                  : 'bg-dark-900 border-dark-700 hover:border-dark-600'
              }`}
            >
              <div className="flex flex-col items-center space-y-3">
                <Users className={`w-12 h-12 ${isFlagSelected('face') ? 'text-orange-400' : 'text-gray-500'}`} />
                <div className="text-center">
                  <p className={`font-semibold ${isFlagSelected('face') ? 'text-orange-400' : 'text-gray-400'}`}>
                    Face Flag
                  </p>
                  <p className="text-xs text-gray-500 mt-1">Multiple faces detected</p>
                </div>
                {isFlagSelected('face') && (
                  <CheckCircle className="w-6 h-6 text-orange-400" />
                )}
              </div>
            </button>

            {/* AI Flag */}
            <button
              onClick={() => toggleFlag('ai')}
              className={`p-6 rounded-lg border-2 transition-all ${
                isFlagSelected('ai')
                  ? 'bg-red-900/30 border-red-600'
                  : 'bg-dark-900 border-dark-700 hover:border-dark-600'
              }`}
            >
              <div className="flex flex-col items-center space-y-3">
                <Bot className={`w-12 h-12 ${isFlagSelected('ai') ? 'text-red-400' : 'text-gray-500'}`} />
                <div className="text-center">
                  <p className={`font-semibold ${isFlagSelected('ai') ? 'text-red-400' : 'text-gray-400'}`}>
                    AI Flag
                  </p>
                  <p className="text-xs text-gray-500 mt-1">Potential AI cheating</p>
                </div>
                {isFlagSelected('ai') && (
                  <CheckCircle className="w-6 h-6 text-red-400" />
                )}
              </div>
            </button>
          </div>

          {/* Selected Flags Summary */}
          <div className="mt-8 p-4 bg-dark-900 rounded-lg border border-dark-700">
            <p className="text-sm text-gray-400 mb-2">Selected Flags:</p>
            {selectedFlags.length > 0 ? (
              <div className="flex flex-wrap gap-2">
                {selectedFlags.map((flag, index) => (
                  <span
                    key={index}
                    className={`px-3 py-1 rounded-full text-sm font-medium ${
                      flag.type === 'sound' ? 'bg-yellow-900/30 text-yellow-400 border border-yellow-800' :
                      flag.type === 'face' ? 'bg-orange-900/30 text-orange-400 border border-orange-800' :
                      'bg-red-900/30 text-red-400 border border-red-800'
                    }`}
                  >
                    {flag.type.toUpperCase()}
                  </span>
                ))}
              </div>
            ) : (
              <p className="text-gray-500 italic">No flags selected - Clean interview</p>
            )}
          </div>
        </div>

        {/* Interview Score Input */}
        <div className="bg-dark-800 rounded-lg shadow-sm border border-dark-700 p-8 mb-8">
          <h3 className="text-xl font-bold text-white mb-6">Interview Score</h3>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-3">
              Score (0-100)
            </label>
            <div className="flex items-center space-x-4">
              <input
                type="range"
                min="0"
                max="100"
                value={interviewScore}
                onChange={(e) => setInterviewScore(parseInt(e.target.value))}
                className="flex-1 h-3 bg-dark-700 rounded-lg appearance-none cursor-pointer accent-primary-600"
              />
              <input
                type="number"
                min="0"
                max="100"
                value={interviewScore}
                onChange={(e) => setInterviewScore(Math.min(100, Math.max(0, parseInt(e.target.value) || 0)))}
                className="w-20 px-4 py-2 bg-dark-900 border border-dark-700 rounded-lg text-white text-center font-semibold focus:outline-none focus:ring-2 focus:ring-primary-500"
              />
            </div>
            <div className="mt-4">
              <div className="w-full bg-dark-700 rounded-full h-3 overflow-hidden">
                <div
                  className={`h-full rounded-full transition-all ${
                    interviewScore >= 90 ? 'bg-green-500' :
                    interviewScore >= 80 ? 'bg-blue-500' :
                    interviewScore >= 70 ? 'bg-yellow-500' : 'bg-orange-500'
                  }`}
                  style={{ width: `${interviewScore}%` }}
                />
              </div>
            </div>
          </div>
        </div>

        {/* Summary Textbox */}
        <div className="bg-dark-800 rounded-lg shadow-sm border border-dark-700 p-8 mb-8">
          <h3 className="text-xl font-bold text-white mb-6">Interview Summary</h3>
          <div>
            <label className="block text-sm font-medium text-gray-300 mb-3">
              AI-Generated Summary
            </label>
            <textarea
              value={summary}
              onChange={(e) => setSummary(e.target.value)}
              rows="6"
              placeholder="Enter interview summary here..."
              className="w-full px-4 py-3 bg-dark-900 border border-dark-700 rounded-lg text-white focus:outline-none focus:ring-2 focus:ring-primary-500 placeholder-gray-600 resize-none"
            />
            <p className="text-xs text-gray-500 mt-2">
              {summary.length} characters
            </p>
          </div>
        </div>

        {/* Info Box */}
        <div className="bg-blue-900/20 border border-blue-800 rounded-lg p-6 mb-8">
          <div className="flex items-start space-x-3">
            <AlertTriangle className="w-6 h-6 text-blue-400 flex-shrink-0 mt-1" />
            <div>
              <h4 className="text-blue-400 font-semibold mb-2">Testing Mode</h4>
              <p className="text-gray-300 text-sm">
                This is a mock interview page for testing purposes. When you submit:
              </p>
              <ul className="text-gray-300 text-sm mt-2 space-y-1 list-disc list-inside">
                <li>Interview score you set will be saved</li>
                <li>Selected flags will be added to your candidate profile</li>
                <li>Status will be updated to "Interviewed"</li>
                <li>Your summary text will be saved</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center space-x-4">
          <button
            onClick={handleSubmitInterview}
            disabled={submitting}
            className="flex-1 flex items-center justify-center space-x-2 px-8 py-4 bg-primary-600 text-white rounded-lg font-semibold hover:bg-primary-500 transition-colors shadow-lg shadow-primary-900/50 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Send className="w-5 h-5" />
            <span>{submitting ? 'Submitting...' : 'Complete Interview'}</span>
          </button>
          <button
            onClick={() => navigate('/applicant/profile')}
            disabled={submitting}
            className="px-8 py-4 border border-dark-600 text-gray-300 rounded-lg font-semibold hover:bg-dark-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Cancel
          </button>
        </div>
      </main>
    </div>
  );
}

export default ApplicantInterview;
